import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextSessionProvider } from '@/context/NextSessionProvider';
import { ChannelProvider } from '@/context/ChannelProvider';
import Footer from '@/components/Footer';
import { FriendsProvider } from '@/context/FriendsProvider';
import { Analytics } from '@vercel/analytics/react';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Messaging App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <NextSessionProvider>
        <ChannelProvider>
          <FriendsProvider>
            <body className={`${inter.className} flex flex-col justify-between`}>
              <Navbar />
              <div className="carousel carousel-vertical h-full">{children}</div>
              <Footer />
              <Analytics />
            </body>
          </FriendsProvider>
        </ChannelProvider>
      </NextSessionProvider>
    </html>
  );
}
